# *** This Dockerfile is generated by the system. You can modify it based on your application requirements *** #
FROM quay.io/klovercloud/gradle:8.11.1-jdk21 AS build
COPY --chown=gradle:gradle . /home/gradle/src

WORKDIR /home/gradle/src

RUN gradle build --no-daemon -x test

FROM quay.io/klovercloud/openjdk:21-jdk

RUN groupadd -g 1001 appgroup && \
    useradd -ms /bin/bash -u 1001 -g appgroup appuser

WORKDIR /home/appuser/app

COPY --from=build /home/gradle/src/build/libs/webhook-java-0.1.0.jar webhook-java.jar

RUN chown -R appuser:appgroup /home/appuser/app

EXPOSE 8080
EXPOSE 8081
USER appuser

ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-Djava.security.egd=file:/dev/./urandom","-jar","/home/appuser/app/webhook-java.jar"]
